main: me.snowman.betterssentials.Betterssentials
name: Betterssentials
author: SnowmanFTW
version: ${project.version}
api-version: 1.13

commands:
  afk:
    description: Afk Command
    usage: /<command> [player]
    permission: betterssentials.afk
    permission-message: "§cYou don't have permission §6betterssentials.afk §cto use this command."
  back:
    description: Back command
    usage: /<command>
    permission: betterssentials.back
    permission-message: "§cYou don't have permission §6betterssentials.back §cto use this command."
  balance:
    description: Balance command
    usage: /<command> [player]
    aliases: [bal]
    permission: betterssentials.balance
    permission-message: "§cYou don't have permission §6betterssentials.balance §cto use this command."
  baltop:
    description: Baltop command
    usage: /<command> [page]
    aliases: [balancetop]
    permission: betterssentials.baltop
    permission-message: "§cYou don't have permission §6betterssentials.baltop §cto use this command."
  ban:
    description: Ban command
    usage: /<command> <player> [reason]
    permission: betterssentials.ban
    permission-message: "§cYou don't have permission §6betterssentials.ban §cto use this command."
  broadcast:
    description: Broadcast command
    usage: /<command> <message>
    aliases: [bc]
    permission: betterssentials.broadcast
    permission-message: "§cYou don't have permission §6betterssentials.broadcast §cto use this command."
  betterssentials:
    description: Betterssentials command
    usage: /<command> <reload>
    aliases: [bess, ess, essentials, be]
    permission: betterssentials.betterssentials
    permission-message: "§cYou don't have permission §6betterssentials.betterssentials §cto use this command."
  clearchat:
    description: ClearChat command
    usage: /<command>
    aliases: [cc]
    permission: betterssentials.clearchat
    permission-message: "§cYou don't have permission §6betterssentials.clearchat §cto use this command."
  clearinventory:
    description: ClearInventory command
    usage: /<command> [player]
    aliases: [ci]
    permission: betterssentials.clearinventory
    permission-message: "§cYou don't have permission §6betterssentials.clearinventory §cto use this command."
  economy:
    description: Economy command
    usage: /<command> <give/take/set/reset> <player> <amount>
    permission: betterssentials.economy
    permission-message: "§cYou don't have permission §6betterssentials.economy §cto use this command."
  enderchest:
    description: Ender Chest command
    usage: /<command> [player]
    aliases: [ec]
    permission: betterssentials.enderchest
    permission-message: "§cYou don't have permission §6betterssentials.enderchest §cto use this command."
  experience:
    description: Experience command
    usage: /<command> <player> [show/set/give] [amount|L<level>]
    aliases: [xp, exp]
    permission: betterssentials.experience
    permission-message: "§cYou don't have permission §6betterssentials.experience §cto use this command."
  feed:
    description: Feed command
    usage: /<command> [player]
    permission: betterssentials.feed
    permission-message: "§cYou don't have permission §6betterssentials.feed §cto use this command."
  fly:
    description: Fly command
    usage: /<command> [player]
    permission: betterssentials.fly
    permission-message: "§cYou don't have permission §6betterssentials.fly §cto use this command."
  gamemode:
    description: Gamemode command
    usage: /<command> <survival/creative/adventure/spectator> <player>
    aliases: [gm]
    permission: betterssentials.gamemode
    permission-message: "§cYou don't have permission §6betterssentials.gamemode §cto use this command."
  give:
    description: Give command
    usage: /<command> <item> <player>
    permission: betterssentials.give
    permission-message: "§cYou don't have permission §6betterssentials.give §cto use this command."
  god:
    description: God command
    usage: /<command> [player]
    aliases: [godmode]
    permission: betterssentials.god
    permission-message: "§cYou don't have permission §6betterssentials.god §cto use this command."
  hat:
    description: Hat command
    usage: /<command>
    permission: betterssentials.hat
    permission-message: "§cYou don't have permission §6betterssentials.god §cto use this command."
  heal:
    description: Heal command
    usage: /<command> [player]
    permission: betterssentials.heal
    permission-message: "§cYou don't have permission §6betterssentials.heal §cto use this command."
  help:
    description: Help command
    usage: /<command> [plugin/page]
  unban:
    description: Unban command
    usage: /<command> <player>
    permission: betterssentials.unban
    permission-message: "§cYou don't have permission §6betterssentials.unban §cto use this command."