main: me.snowman.betterssentials.Betterssentials
name: Betterssentials
author: SnowmanFTW
version: ${project.version}
api-version: 1.13

commands:
  afk:
    description: Afk Command
    usage: /<command> [player]
    permission: betterssentials.afk
    permission-message: "§cYou don't have permission §6betterssentials.afk §cto use this command."
  back:
    description: Back command
    usage: /<command>
    permission: betterssentials.back
    permission-message: "§cYou don't have permission §6betterssentials.back §cto use this command."
  balance:
    description: Balance command
    usage: /<command> [player]
    aliases: [bal]
    permission: betterssentials.balance
    permission-message: "§cYou don't have permission §6betterssentials.balance §cto use this command."
  baltop:
    description: Baltop command
    usage: /<command> [page]
    aliases: [balancetop]
    permission: betterssentials.baltop
    permission-message: "§cYou don't have permission §6betterssentials.baltop §cto use this command."
  ban:
    description: Ban command
    usage: /<command> <player> [reason]
    permission: betterssentials.ban
    permission-message: "§cYou don't have permission §6betterssentials.ban §cto use this command."
  broadcast:
    description: Broadcast command
    usage: /<command> <message>
    aliases: [bc]
    permission: betterssentials.broadcast
    permission-message: "§cYou don't have permission §6betterssentials.broadcast §cto use this command."
  betterssentials:
    description: Betterssentials command
    usage: /<command> <reload>
    aliases: [bess, ess, essentials, be]
    permission: betterssentials.betterssentials
    permission-message: "§cYou don't have permission §6betterssentials.betterssentials §cto use this command."
  clearchat:
    description: ClearChat command
    usage: /<command>
    aliases: [cc]
    permission: betterssentials.clearchat
    permission-message: "§cYou don't have permission §6betterssentials.clearchat §cto use this command."
  clearinventory:
    description: ClearInventory command
    usage: /<command> [player]
    aliases: [ci]
    permission: betterssentials.clearinventory
    permission-message: "§cYou don't have permission §6betterssentials.clearinventory §cto use this command."
  economy:
    description: Economy command
    usage: /<command> <give/take/set/reset> <player> <amount>
    aliases: [eco]
    permission: betterssentials.economy
    permission-message: "§cYou don't have permission §6betterssentials.economy §cto use this command."
  enderchest:
    description: Ender Chest command
    usage: /<command> [player]
    aliases: [ec]
    permission: betterssentials.enderchest
    permission-message: "§cYou don't have permission §6betterssentials.enderchest §cto use this command."
  experience:
    description: Experience command
    usage: /<command> <player> [show/set/give] [amount|L<level>]
    aliases: [xp, exp]
    permission: betterssentials.experience
    permission-message: "§cYou don't have permission §6betterssentials.experience §cto use this command."
  feed:
    description: Feed command
    usage: /<command> [player]
    permission: betterssentials.feed
    permission-message: "§cYou don't have permission §6betterssentials.feed §cto use this command."
  fly:
    description: Fly command
    usage: /<command> [player]
    permission: betterssentials.fly
    permission-message: "§cYou don't have permission §6betterssentials.fly §cto use this command."
  gamemode:
    description: Gamemode command
    usage: /<command> <survival/creative/adventure/spectator> <player>
    aliases: [gm]
    permission: betterssentials.gamemode
    permission-message: "§cYou don't have permission §6betterssentials.gamemode §cto use this command."
  gms:
    description: Gms command
    usage: /<command> [player]
    permission: betterssentials.gamemode.survival
    permission-message: "§cYou don't have permission §6betterssentials.gamemode.survival §cto use this command."
  gma:
    description: Gma command
    usage: /<command> [player]
    permission: betterssentials.gamemode.adventure
    permission-message: "§cYou don't have permission §6betterssentials.gamemode.adventure §cto use this command."
  gmc:
    description: Gmc command
    usage: /<command> [player]
    permission: betterssentials.gamemode.creative
    permission-message: "§cYou don't have permission §6betterssentials.gamemode.creative §cto use this command."
  gmsp:
    description: Gmsp command
    usage: /<command> [player]
    permission: betterssentials.gamemode.spectator
    permission-message: "§cYou don't have permission §6betterssentials.gamemode.spectator §cto use this command."
  give:
    description: Give command
    usage: /<command> <item> <player>
    permission: betterssentials.give
    permission-message: "§cYou don't have permission §6betterssentials.give §cto use this command."
  god:
    description: God command
    usage: /<command> [player]
    aliases: [godmode]
    permission: betterssentials.god
    permission-message: "§cYou don't have permission §6betterssentials.god §cto use this command."
  hat:
    description: Hat command
    usage: /<command>
    permission: betterssentials.hat
    permission-message: "§cYou don't have permission §6betterssentials.god §cto use this command."
  heal:
    description: Heal command
    usage: /<command> [player]
    permission: betterssentials.heal
    permission-message: "§cYou don't have permission §6betterssentials.heal §cto use this command."
  help:
    description: Help command
    usage: /<command> [plugin/page]
  invsee:
    description: Invsee command
    usage: /<command> <player>
    aliases: [inventorysee]
    permission: betterssentials.invsee
    permission-message: "§cYou don't have permission §6betterssentials.invsee §cto use this command."
  kick:
    description: Kick command
    usage: /<command> <player> [reason]
    permission: betterssentials.kick
    permission-message: "§cYou don't have permission §6betterssentials.kick §cto use this command."
  kickall:
    description: Kickall command
    usage: /<command> [reason]
    permission: betterssentials.kickall
    permission-message: "§cYou don't have permission §6betterssentials.kickall §cto use this command."
  kill:
    description: Kill command
    usage: /<command> <player>
    permission: betterssentials.kill
    permission-message: "§cYou don't have permission §6betterssentials.kill §cto use this command."
  killall:
    description: Killall command
    usage: /<command>
    permission: betterssentials.killall
    permission-message: "§cYou don't have permission §6betterssentials.killall §cto use this command."
  list:
    description: List command
    usage: /<command>
  me:
    description: Me command
    usage: /<command> <description>
    permission: betterssentials.me
    permission-message: "§cYou don't have permission §6betterssentials.me §cto use this command."
  mute:
    description: Mute command
    usage: /<command> <player> [time s/m/h]
    permission: betterssentials.mute
    permission-message: "§cYou don't have permission §6betterssentials.mute §cto use this command."
  nick:
    description: Nick command
    usage: /<command> [player] <nickname/off>
    permission: betterssentials.nick
    permission-message: "§cYou don't have permission §6betterssentials.nick §cto use this command."
  pay:
    description: Pay command
    usage: /<command> <player> <amount>
    permission: betterssentials.pay
    permission-message: "§cYou don't have permission §6betterssentials.pay §cto use this command."
  realname:
    description: Realname command
    usage: /<command> <player>
    permission: betterssentials.realname
    permission-message: "§cYou don't have permission §6betterssentials.realname §cto use this command."
  repair:
    description: Repair command
    usage: /<command> <hand/all>
    permision: betterssentials.repair
    permission-message: "§cYou don't have permission §6betterssentials.repair §cto use this command."
  skull:
    description: Skull command
    usage: /<command> <name>
    permission: betterssentials.skull
    permission-message: "§cYou don't have permission §6betterssentials.skull §cto use this command."
  speed:
    description: Speed command
    usage: /<command> <0-10> [fly/walk] [player]
    permission: betterssentials.speed
    permission-message: "§cYou don't have permission §6betterssentials.speed §cto use this command."
  unban:
    description: Unban command
    usage: /<command> <player>
    permission: betterssentials.unban
    permission-message: "§cYou don't have permission §6betterssentials.unban §cto use this command."
  unmute:
    description: Unmute command
    usage: /<command> <player>
    permission: betterssentials.unmute
    permission-message: "§cYou don't have permission §6betterssentials.unmute §cto use this command."